version: '2'
services:
  redis:
    image: redis:latest
    ports:
      - 3679:6379
    networks:
      - mynetwork

  bot1:
    image: ping-bot:3.10
    environment:
      - TOKEN_BOT=
      - REDIS_HOST=
      - REDIS_PORT=
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge