version: '2'
services:
  redis:
    image: redis
    ports:
      - 3679:6379 # default port
    networks:
      - mynetwork

  bot1:
    image: # your image
    environment:
      - TOKEN_BOT= # your token
      - REDIS_HOST=host.docker. # name your services /redis 
      - REDIS_PORT= # default port 6379
    restart: always
    depends_on:
      - redis
    links:
      - redis:host.docker.redis # ( name your services:host.docker.name your services )
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge